<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <NoWarn>NETSDK1138;1591</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>ENCY</Authors>
    <PackageId>EncySoftware.PunchingOperation</PackageId>
    <PackageTags>ency-extension;operationsolver</PackageTags>
    <Description>New operation, which calculates 6 degree of freedom toolpath. The user can define set of planar curves like rectangles, stars or circles in the Job assignment. The operation recognizes shape, corners of each shape and orients the punch end effector to match the corners on the punch with the corners on the original outline.</Description>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/EncySoftware/PunchingOperation</PackageProjectUrl>
    <RepositoryUrl>https://github.com/EncySoftware/PunchingOperation</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="2.0.17-dev.9" />
  </ItemGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\"/>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="PunchingOperation_ExtOp.xml" Pack="true" PackagePath="contentFiles\any\any\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>  
    <None Include="PunchingOperationExtension.settings.json" Pack="true" PackagePath="contentFiles\any\any\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>